const RankingData = {
    "track1": [
        {
            "team_name": "IPIU_VQA",
            "leader_name": "Zhicheng Guo",
            "team_org": "Xidian University",
            "team_size": 4,
        },
        {
            "team_name": "Go For It",
            "leader_name": "Jiahao Wang",
            "team_org": "Xidian University",
            "team_size": 4,
        },
        {
            "team_name": "mote",
            "leader_name": "zhangfuwei",
            "team_org": "Sun Yat-sen University",
            "team_size": 3,
        },
        {
            "team_name": "VL",
            "leader_name": "Haonan Zhang",
            "team_org": "University of Electronic Science and Technology of China",
            "team_size": 4,
        },
        {
            "team_name": "no name",
            "leader_name": "武祥宇",
            "team_org": "NJUST",
            "team_size": 5,
        },
        {
            "team_name": "BOE_AIOT_CTO",
            "leader_name": "wangbinqian",
            "team_org": "BOE Technology  Co., Ltd. ",
            "team_size": 2,
        },
        {
            "team_name": "TEMP",
            "leader_name": "Yujie Mo",
            "team_org": "UESTC",
            "team_size": 1,
        },
        {
            "team_name": "WH-VQA",
            "leader_name": "Hui Wang",
            "team_org": "Hefei University of Technology",
            "team_size": 1,
        },
        {
            "team_name": "admin5111",
            "leader_name": "Xintian Wu",
            "team_org": "Zhejiang University",
            "team_size": 1,
        },
        {
            "team_name": "Flyegle",
            "leader_name": "mingchao jiang",
            "team_org": "Guangdong University of Technology",
            "team_size": 1,
        },
        {
            "team_name": "Zhiyong Team",
            "leader_name": "Dxwell",
            "team_org": "HNU | HNU | HNU | HNU",
            "team_size": 4,
        },
        {
            "team_name": "mmx",
            "leader_name": "mmx",
            "team_org": "长春大学",
            "team_size": 1,
        },
        {
            "team_name": "kafka",
            "leader_name": "Hailong Yang",
            "team_org": "myself",
            "team_size": 1,
        },
        {
            "team_name": "zyfanzy",
            "leader_name": "Zhongyi Fan",
            "team_org": "Beijing Institute of Technology",
            "team_size": 1,
        },
        {
            "team_name": "ACC",
            "leader_name": "Wang Bing",
            "team_org": "Communication University of China",
            "team_size": 1,
        },
        {
            "team_name": "wateryu",
            "leader_name": "liu xinyu",
            "team_org": "Harbin University of Science and Technology",
            "team_size": 1,
        },
        {
            "team_name": "tfq568897492",
            "leader_name": "xiaoming jiang",
            "team_org": "zhimu keji",
            "team_size": 1,
        },
        {
            "team_name": "runone (9342)",
            "leader_name": "runone",
            "team_org": "runone",
            "team_size": 1,
        },
        {
            "team_name": "matlab-ustb",
            "leader_name": "Chenghao Guo",
            "team_org": "University of Science and Technology Beijing",
            "team_size": 3,
        },
        {
            "team_name": "laoxu",
            "leader_name": "xubowen",
            "team_org": "Alibaba",
            "team_size": 1,
        },
        {
            "team_name": "SadFr0gs",
            "leader_name": "Liying Chi",
            "team_org": "None | University of Utah",
            "team_size": 2,
        },
        {
            "team_name": "A Rowing Boat",
            "leader_name": "Cong Wu",
            "team_org": "Jiangnan University",
            "team_size": 3,
        },
        {
            "team_name": "June",
            "leader_name": "Zhiyuan Ma",
            "team_org": "None",
            "team_size": 1,
        },
        {
            "team_name": "hust1112",
            "leader_name": "liu",
            "team_org": "HUST",
            "team_size": 2,
        },
        {
            "team_name": "HSSLAB",
            "leader_name": "Baoyu Fan",
            "team_org": "INSPUR",
            "team_size": 4,
        },
        {
            "team_name": "NoManCanControl",
            "leader_name": "Hui Fu",
            "team_org": "Northwestern Polytechnical University",
            "team_size": 1,
        },
        {
            "team_name": "bang",
            "leader_name": "gunanxi",
            "team_org": "baidu",
            "team_size": 1,
        },
        {
            "team_name": "seu_gzh",
            "leader_name": "Guo ZongHui",
            "team_org": "Southeast University",
            "team_size": 1,
        },
        {
            "team_name": "TeamHe",
            "leader_name": "Junjie He",
            "team_org": "Zhejiang University",
            "team_size": 1,
        },
        {
            "team_name": "increase",
            "leader_name": "Jia Zeng",
            "team_org": "Shanghai Jiao Tong University",
            "team_size": 1,
        },
        {
            "team_name": "runone (Dian Liu)",
            "leader_name": "Dian Liu",
            "team_org": "Runone | Runone",
            "team_size": 2,
        },
        {
            "team_name": "ImageTru3d",
            "leader_name": "Baoping Li",
            "team_org": "ImageTru3d",
            "team_size": 1,
        },
        {
            "team_name": "SYSU_HCP",
            "leader_name": "YangLiu",
            "team_org": "Sun Yat-Sen University | Sun Yat-Sen University",
            "team_size": 2,
        },
        {
            "team_name": "NIMA",
            "leader_name": "Eric Du",
            "team_org": "JINCROP",
            "team_size": 1,
        },
        {
            "team_name": "MiemieSheep",
            "leader_name": "Wenxuan Liu",
            "team_org": "Wuhan University of Technology",
            "team_size": 4,
        },
        {
            "team_name": "KOKOKO",
            "leader_name": "pengmin",
            "team_org": "The University of Chinese Academy of Sciences",
            "team_size": 1,
        },
        {
            "team_name": "Gogogo",
            "leader_name": "Hoang-Anh Pham",
            "team_org": "Applied Artificial Intelligence Institute (A²I²), Deakin University",
            "team_size": 1,
        },
        {
            "team_name": "GoodAI",
            "leader_name": "Qiu Yuqing",
            "team_org": "OPPO",
            "team_size": 2,
        },
        {
            "team_name": "daxia",
            "leader_name": "mengwei",
            "team_org": "Alibaba",
            "team_size": 1,
        },
        {
            "team_name": "NWPU_FlyingForDream",
            "leader_name": "Chao Li",
            "team_org": "Northwestern Polytechnical University",
            "team_size": 5,
        },
        {
            "team_name": "Jingyu Xie",
            "leader_name": "jingyu Xie",
            "team_org": "TUM",
            "team_size": 1,
        },
        {
            "team_name": "HalfDriedHerring",
            "leader_name": "Tackgeun You",
            "team_org": "POSTECH",
            "team_size": 1,
        },
        {
            "team_name": "TESTING",
            "leader_name": "TESTING",
            "team_org": "FOR TESTING ONLY",
            "team_size": 1,
        },
        {
            "team_name": "HCMUS-HGV",
            "leader_name": "Quoc Huy Trinh",
            "team_org": "Ho Chi Minh University of Science",
            "team_size": 3,
        },
        {
            "team_name": "ABCDE",
            "leader_name": "Jingru Wang",
            "team_org": "BOE",
            "team_size": 1,
        },
        {
            "team_name": "你笑起来真好看",
            "leader_name": "Zhengjian Wu",
            "team_org": "Xinjiang University",
            "team_size": 3,
        },
        {
            "team_name": "VisionX (Yuqiao)",
            "leader_name": "Yuqiao Xian",
            "team_org": "Sun Yat-sen University",
            "team_size": 1,
        },
        {
            "team_name": "underline",
            "leader_name": "Xiaoyu Zhu",
            "team_org": "Carnegie Mellon University",
            "team_size": 1,
        },
        {
            "team_name": "AI is an art",
            "leader_name": "白宗文",
            "team_org": "Yan'an University",
            "team_size": 4,
        },
        {
            "team_name": "TaTa",
            "leader_name": "Yuhan Wang",
            "team_org": "Xidian University",
            "team_size": 4,
        },
        {
            "team_name": "UPCer",
            "leader_name": "Jing Lu",
            "team_org": "China University of Petroleum Huadong",
            "team_size": 1,
        },
        {
            "team_name": "ZHUYT",
            "leader_name": "yitao 朱",
            "team_org": "Shanghai University of Electric Power",
            "team_size": 1,
        },
        {
            "team_name": "NjTechCVLab",
            "leader_name": "Zijie Wang",
            "team_org": "Nanjing Tech University",
            "team_size": 5,
         }
    ],
    "track2": [
        {
            "team_name": "A Rowing Boat",
            "leader_name": "Cong Wu",
            "team_org": "Jiangnan University | University Of Surrey | Tsinghua University",
            "team_size": 7,
        },
        {
            "team_name": "322Win",
            "leader_name": "Jinlu Zhang",
            "team_org": "Wuhan University | Shenzhen Infinova Ltd",
            "team_size": 6,
        },
        {
            "team_name": "CRIPAC",
            "leader_name": "Liang Wang",
            "team_org": "Institute of Automation, Chinese Academy of Sciences | University of Chinese Academy of Sciences | Beijing University of Posts and Telecommunications",
            "team_size": 4,
        },
        {
            "team_name": "Knights",
            "leader_name": "Zhan Chen",
            "team_org": "Peking University | the School of Intelligent Systems Engineering, Sun Yat-sen University",
            "team_size": 4,
        },
        {
            "team_name": "huqianshuo",
            "leader_name": "HU qianshuo",
            "team_org": "Chongqing University of Technology",
            "team_size": 1,
        },
        {
            "team_name": "F&T",
            "leader_name": "Di Yang",
            "team_org": "INRIA",
            "team_size": 4,
        },
        {
            "team_name": "COST",
            "leader_name": "Yonghao Dang",
            "team_org": "Beijing University of Posts and Telecommunications",
            "team_size": 10,
        },
        {
            "team_name": "WHU322",
            "leader_name": "Jiaxu Zhang",
            "team_org": "Wuhan University",
            "team_size": 1,
        },
        {
            "team_name": "YUYO",
            "leader_name": "Junying Wang",
            "team_org": "Beijing University of Posts and Telecommunications",
            "team_size": 1,
        },
        {
            "team_name": "xxx2333",
            "leader_name": "陈亭秀",
            "team_org": "Beijing University of Posts and Telecommunications",
            "team_size": 1,
        },
        {
            "team_name": "lambdA",
            "leader_name": "Jin Liu",
            "team_org": "Beijing University of Posts and Telecommunications",
            "team_size": 1,
        },
        {
            "team_name": "HAG",
            "leader_name": "Xuanhan Wang",
            "team_org": "UESTC",
            "team_size": 1,
        },
        {
            "team_name": "小小令狐冲",
            "leader_name": "xing kai",
            "team_org": "University of Electronic Science and Technology of China",
            "team_size": 1,
        },
        {
            "team_name": "NUC",
            "leader_name": "Chuankun Li",
            "team_org": "North University of China | Shandong University | Shandong University | University of Wollongong",
            "team_size": 4,
        },
        {
            "team_name": "Bingoooo",
            "leader_name": "刘孝发",
            "team_org": "Beijing University of Posts and Telecommunications",
            "team_size": 1,
        },
        {
            "team_name": "KIDO",
            "leader_name": "Jin Zhang",
            "team_org": "Beijing University of Posts and Telecommunications",
            "team_size": 1,
        },
        {
            "team_name": "SIAT_HMC",
            "leader_name": "Qin Cheng",
            "team_org": "Shenzhen Institute of Advanced Technology，Chinese Academy of Sciences",
            "team_size": 3,
        },
        {
            "team_name": "RMaster",
            "leader_name": "Yunheng Li",
            "team_org": "Dalian University of Technology",
            "team_size": 2,
        },
        {
            "team_name": "ComvisHUST",
            "leader_name": "Thi-Lan Le",
            "team_org": "SET, HUST",
            "team_size": 7,
        },
        {
            "team_name": "LX",
            "leader_name": "LX-DLUT",
            "team_org": "Dalian University of Technology",
            "team_size": 1,
        },
        {
            "team_name": "Y1S1_China_Dragon",
            "leader_name": "Rui Wang",
            "team_org": "Jiangnan University",
            "team_size": 4,
        },
        {
            "team_name": "Signed/OB",
            "leader_name": "Emanuel Rapsch",
            "team_org": "TU Berlin | HU Berlin | U Oxford | Imperial College London | U Oxford | U Oxford",
            "team_size": 7,
        },
        {
            "team_name": "LL",
            "leader_name": "Li Xiang",
            "team_org": "Dalian University of Technology",
            "team_size": 1,
        },
        {
            "team_name": "CMIT",
            "leader_name": "Jiashuo Yu",
            "team_org": "Fudan University",
            "team_size": 1,
        },
        {
            "team_name": "jiangnan",
            "leader_name": "Cheng NanJiang",
            "team_org": "Chengdu University of Information Technology",
            "team_size": 1,
        },
        {
            "team_name": "cv208",
            "leader_name": "Sun Xiaoyue",
            "team_org": "Northeast Petroleum University",
            "team_size": 1,
        },
        {
            "team_name": "Just Know ABC",
            "leader_name": "李卓",
            "team_org": "China University of Petroleum (Huadong)",
            "team_size": 1,
        },
        {
            "team_name": "ETVP",
            "leader_name": "WangNing",
            "team_org": "Xidian University",
            "team_size": 1,
        },
        {
            "team_name": "kafka",
            "leader_name": "Hailong Yang",
            "team_org": "myself",
            "team_size": 1,
        },
        {
            "team_name": "cumt_306",
            "leader_name": "laingjian",
            "team_org": "cumt",
            "team_size": 1,
        },
        {
            "team_name": "tfq568897492",
            "leader_name": "xiaoming jiang",
            "team_org": "zhimu keji",
            "team_size": 1,
        },
        {
            "team_name": "YNUVMC",
            "leader_name": "Yanan Liu",
            "team_org": "Yunnan University",
            "team_size": 1,
        },
        {
            "team_name": "Jun",
            "leader_name": "Liu Guangjun",
            "team_org": "Xi'an Jiaotong university",
            "team_size": 1,
        },
        {
            "team_name": "runone (9342)",
            "leader_name": "runone",
            "team_org": "runone",
            "team_size": 1,
        },
        {
            "team_name": "owner",
            "leader_name": "Liu Bo",
            "team_org": "SiChuan University",
            "team_size": 3,
        },
        {
            "team_name": "1024",
            "leader_name": "will",
            "team_org": "bohui",
            "team_size": 1,
        },
        {
            "team_name": "SadFr0gs",
            "leader_name": "Liying Chi",
            "team_org": "None | University of Utah",
            "team_size": 2,
        },
        {
            "team_name": "June",
            "leader_name": "Zhiyuan Ma",
            "team_org": "None",
            "team_size": 1,
        },
        {
            "team_name": "416gogo",
            "leader_name": "liangduohan",
            "team_org": "JD.com | Xi'an University of Technology | Xi'an University of Technology",
            "team_size": 3,
        },
        {
            "team_name": "HSSLAB",
            "leader_name": "Baoyu Fan",
            "team_org": "INSPUR",
            "team_size": 4,
        },
        {
            "team_name": "NoManCanControl",
            "leader_name": "Hui Fu",
            "team_org": "Northwestern Polytechnical University",
            "team_size": 1,
        },
        {
            "team_name": "Go for ReID",
            "leader_name": "Ruofei Gao",
            "team_org": "China Mobile Research Institute",
            "team_size": 2,
        },
        {
            "team_name": "TeamHe",
            "leader_name": "Junjie He",
            "team_org": "Zhejiang University",
            "team_size": 1,
        },
        {
            "team_name": "increase",
            "leader_name": "Jia Zeng",
            "team_org": "Shanghai Jiao Tong University",
            "team_size": 1,
        },
        {
            "team_name": "daydayup",
            "leader_name": "JUNJIE HOU",
            "team_org": "Yanshan University",
            "team_size": 1,
        },
        {
            "team_name": "nancyteam",
            "leader_name": "chen li",
            "team_org": "banma wangluo",
            "team_size": 1,
        },
        {
            "team_name": "吃不到葡萄吃樱桃",
            "leader_name": "李成辉",
            "team_org": "Xidian University",
            "team_size": 3,
        },
        {
            "team_name": "NGCLAB",
            "leader_name": "Liyang Zheng",
            "team_org": "Zhejiang University",
            "team_size": 2,
        },
        {
            "team_name": "ImageTru3d",
            "leader_name": "Baoping Li",
            "team_org": "ImageTru3d",
            "team_size": 1,
        },
        {
            "team_name": "MiemieSheep",
            "leader_name": "Wenxuan Liu",
            "team_org": "Wuhan University of Technology",
            "team_size": 4,
        },
        {
            "team_name": "CCCit",
            "leader_name": "Neo Chen",
            "team_org": "Alibaba",
            "team_size": 1,
        },
        {
            "team_name": "Woo!",
            "leader_name": "NingWang",
            "team_org": "School of Computer Science and Technology, Xidian University, China",
            "team_size": 1,
        },
        {
            "team_name": "Nourelmadany",
            "leader_name": "Noureldin Elmadany",
            "team_org": "AAST",
            "team_size": 1,
        },
        {
            "team_name": "GoodAI",
            "leader_name": "Qiu Yuqing",
            "team_org": "OPPO",
            "team_size": 2,
        },
        {
            "team_name": "CPVR2050",
            "leader_name": "GAOFENG",
            "team_org": "Beijing University of Post and Telecommunications",
            "team_size": 1,
        },
        {
            "team_name": "R",
            "leader_name": "Renshu Gu",
            "team_org": "Hangzhou Dianzi University",
            "team_size": 1,
        },
        {
            "team_name": "NWPU_FlyingForDream",
            "leader_name": "Chao Li",
            "team_org": "Northwestern Polytechnical University",
            "team_size": 5,
        },
        {
            "team_name": "DCI-ETRI",
            "leader_name": "Soonyong Song",
            "team_org": "Electronics and Telecommunications Research Institute",
            "team_size": 2,
        },
        {
            "team_name": "TESTING",
            "leader_name": "TESTING",
            "team_org": "FOR TESTING ONLY",
            "team_size": 1,
        },
        {
            "team_name": "ABCDE",
            "leader_name": "Jingru Wang",
            "team_org": "BOE",
            "team_size": 1,
        },
        {
            "team_name": "RogersAI",
            "leader_name": "Wei-Yi Chang",
            "team_org": "RogersAI Technology",
            "team_size": 1,
        },
        {
            "team_name": "HUST AIA Smart Group",
            "leader_name": "Bo Tan",
            "team_org": "School of Artificial Intelligence and Automation of Huazhong University of Science and Technology, Wuhan, China | AI Lab , ByteDance Inc.,China |  Institute of High Performance Computing, Research Agency for Science, Technology, and Research, Singapore",
            "team_size": 8,
        },
        {
            "team_name": "你笑起来真好看",
            "leader_name": "Zhengjian Wu",
            "team_org": "Xinjiang University",
            "team_size": 3,
        },
        {
            "team_name": "VisionX (Yuqiao)",
            "leader_name": "Yuqiao Xian",
            "team_org": "Sun Yat-sen University",
            "team_size": 1,
        },
        {
            "team_name": "underline",
            "leader_name": "Xiaoyu Zhu",
            "team_org": "Carnegie Mellon University",
            "team_size": 1,
        },
        {
            "team_name": "ByteScene",
            "leader_name": "Zhibin Xiao",
            "team_org": "Bytedance Inc.",
            "team_size": 1,
        },
        {
            "team_name": "BIGbear",
            "leader_name": "Xiong Li",
            "team_org": "CETC",
            "team_size": 1,
        },
        {
            "team_name": "AIWorker",
            "leader_name": "Senquan Yang",
            "team_org": "Shenzhen University",
            "team_size": 1,
        },
        {
            "team_name": "scnu",
            "leader_name": "Yang",
            "team_org": "SCNU",
            "team_size": 1,
        },
        {
            "team_name": "AI is an art",
            "leader_name": "白宗文",
            "team_org": "Yan'an University",
            "team_size": 4,
        },
        {
            "team_name": "MSU",
            "leader_name": "Yusuf Erkan Gorgulu",
            "team_org": "Milli Savunma Universitesi",
            "team_size": 1,
        },
        {
            "team_name": "TaTa",
            "leader_name": "Yuhan Wang",
            "team_org": "Xidian University",
            "team_size": 4,
        },
        {
            "team_name": "IPIU_VQA",
            "leader_name": "Zhicheng Guo",
            "team_org": "Xidian University",
            "team_size": 4,
        },
        {
            "team_name": "aiforward",
            "leader_name": "zhangxu",
            "team_org": "aiforward",
            "team_size": 2,
         }
    ],
    "track3": [
        {
            "team_name": "A Rowing Boat",
            "leader_name": "Cong Wu",
            "team_org": "Jiangnan University | University Of Surrey | Tsinghua University",
            "team_size": 7,
        },
        {
            "team_name": "t322",
            "leader_name": "Zhiran",
            "team_org": "Wuhan University | Shenzhen Infinova Ltd",
            "team_size": 7,
        },
        {
            "team_name": "BOE_AIOT_AIBD",
            "leader_name": "Xianbin Liu",
            "team_org": "BOE Technology Group Co., Ltd",
            "team_size": 3,
        },
        {
            "team_name": "HUST AIA Smart Group",
            "leader_name": "Bo Tan",
            "team_org": "School of Artificial Intelligence and Automation of Huazhong University of Science and Technology, Wuhan, China | AI Lab , ByteDance Inc.,China |  Institute of High Performance Computing, Research Agency for Science, Technology, and Research, Singapore",
            "team_size": 8,
        },
        {
            "team_name": "Lurchy",
            "leader_name": "Zhe li",
            "team_org": "HuaQiao University",
            "team_size": 3,
        },
        {
            "team_name": "CMIT",
            "leader_name": "Jiashuo Yu",
            "team_org": "Fudan University",
            "team_size": 1,
        },
        {
            "team_name": "F&T",
            "leader_name": "Di Yang",
            "team_org": "INRIA",
            "team_size": 4,
        },
        {
            "team_name": "大佬带带我",
            "leader_name": "SHAO Huixiang",
            "team_org": "Waseda University | ShangHai university",
            "team_size": 2,
        },
        {
            "team_name": "沙雕之魂",
            "leader_name": "郭龙银",
            "team_org": "四川大学视觉合成实验室",
            "team_size": 1,
        },
        {
            "team_name": "Wuyi_university_jnlab",
            "leader_name": "Yunlong Li",
            "team_org": "Wuyi university",
            "team_size": 1,
        },
        {
            "team_name": "CD",
            "leader_name": "yz_Jason",
            "team_org": "Huazhong University of Science and Technology",
            "team_size": 1,
        },
        {
            "team_name": "cv208",
            "leader_name": "Sun Xiaoyue",
            "team_org": "Northeast Petroleum University",
            "team_size": 1,
        },
        {
            "team_name": "ETVP",
            "leader_name": "WangNing",
            "team_org": "Xidian University",
            "team_size": 1,
        },
        {
            "team_name": "kafka",
            "leader_name": "Hailong Yang",
            "team_org": "myself",
            "team_size": 1,
        },
        {
            "team_name": "tfq568897492",
            "leader_name": "xiaoming jiang",
            "team_org": "zhimu keji",
            "team_size": 1,
        },
        {
            "team_name": "runone (9342)",
            "leader_name": "runone",
            "team_org": "runone",
            "team_size": 1,
        },
        {
            "team_name": "HDU_CS",
            "leader_name": "Jun Bao",
            "team_org": "Hangzhou Dianzi University | NEC lab America",
            "team_size": 3,
        },
        {
            "team_name": "1024",
            "leader_name": "will",
            "team_org": "bohui",
            "team_size": 1,
        },
        {
            "team_name": "June",
            "leader_name": "Zhiyuan Ma",
            "team_org": "None",
            "team_size": 1,
        },
        {
            "team_name": "HSSLAB",
            "leader_name": "Baoyu Fan",
            "team_org": "INSPUR",
            "team_size": 4,
        },
        {
            "team_name": "NoManCanControl",
            "leader_name": "Hui Fu",
            "team_org": "Northwestern Polytechnical University",
            "team_size": 1,
        },
        {
            "team_name": "TeamHe",
            "leader_name": "Junjie He",
            "team_org": "Zhejiang University",
            "team_size": 1,
        },
        {
            "team_name": "ImageTru3d",
            "leader_name": "Baoping Li",
            "team_org": "ImageTru3d",
            "team_size": 1,
        },
        {
            "team_name": "FF",
            "leader_name": "Stefan Liu",
            "team_org": "FF",
            "team_size": 1,
        },
        {
            "team_name": "MiemieSheep",
            "leader_name": "Wenxuan Liu",
            "team_org": "Wuhan University of Technology",
            "team_size": 4,
        },
        {
            "team_name": "FAR",
            "leader_name": "Melvin Maonn",
            "team_org": "China Merchants Bank",
            "team_size": 1,
        },
        {
            "team_name": "CCCit",
            "leader_name": "Neo Chen",
            "team_org": "Alibaba",
            "team_size": 1,
        },
        {
            "team_name": "Woo!",
            "leader_name": "NingWang",
            "team_org": "School of Computer Science and Technology, Xidian University, China",
            "team_size": 1,
        },
        {
            "team_name": "Nourelmadany",
            "leader_name": "Noureldin Elmadany",
            "team_org": "AAST",
            "team_size": 1,
        },
        {
            "team_name": "SIAT_HMC",
            "leader_name": "Qin Cheng",
            "team_org": "Shenzhen Institute of Advanced Technology，Chinese Academy of Sciences",
            "team_size": 3,
        },
        {
            "team_name": "GoodAI",
            "leader_name": "Qiu Yuqing",
            "team_org": "OPPO",
            "team_size": 2,
        },
        {
            "team_name": "NWPU_FlyingForDream",
            "leader_name": "Chao Li",
            "team_org": "Northwestern Polytechnical University",
            "team_size": 5,
        },
        {
            "team_name": "Jingyu Xie",
            "leader_name": "jingyu Xie",
            "team_org": "TUM",
            "team_size": 1,
        },
        {
            "team_name": "soso",
            "leader_name": "Xiaolin Song",
            "team_org": "Tianjin University",
            "team_size": 1,
        },
        {
            "team_name": "TESTING",
            "leader_name": "TESTING",
            "team_org": "FOR TESTING ONLY",
            "team_size": 1,
        },
        {
            "team_name": "HCMUS-HGV",
            "leader_name": "Quoc Huy Trinh",
            "team_org": "Ho Chi Minh University of Science",
            "team_size": 3,
        },
        {
            "team_name": "ABCDE",
            "leader_name": "Jingru Wang",
            "team_org": "BOE",
            "team_size": 1,
        },
        {
            "team_name": "你笑起来真好看",
            "leader_name": "Zhengjian Wu",
            "team_org": "Xinjiang University",
            "team_size": 3,
        },
        {
            "team_name": "VisionX (Yuqiao)",
            "leader_name": "Yuqiao Xian",
            "team_org": "Sun Yat-sen University",
            "team_size": 1,
        },
        {
            "team_name": "underline",
            "leader_name": "Xiaoyu Zhu",
            "team_org": "Carnegie Mellon University",
            "team_size": 1,
        },
        {
            "team_name": "ByteScene",
            "leader_name": "Zhibin Xiao",
            "team_org": "Bytedance Inc.",
            "team_size": 1,
        },
        {
            "team_name": "+1star",
            "leader_name": "Xu Yuecong",
            "team_org": "Institute for Infocomm Research (I2R), Agency for Sciency, Technology and Research (A*STAR) | School of Electrical and Electronic Engineering, Nanyang Technological University, Singapore | School of Electrical and Electronic Engineering, Nanyang Technological University, Singapore",
            "team_size": 6,
        },
        {
            "team_name": "TaTa",
            "leader_name": "Yuhan Wang",
            "team_org": "Xidian University",
            "team_size": 4,
        },
        {
            "team_name": "IPIU_VQA",
            "leader_name": "Zhicheng Guo",
            "team_org": "Xidian University",
            "team_size": 4,
        },
        {
            "team_name": "Knights",
            "leader_name": "Zhan Chen",
            "team_org": "Peking University | the School of Intelligent Systems Engineering, Sun Yat-sen University",
            "team_size": 4,
        },
        {
            "team_name": "FightXZ",
            "leader_name": "xuanzhao",
            "team_org": "CAMA ",
            "team_size": 1,
         }
    ],
    "track4": [
        {
            "team_name": "MARS_WHU",
            "leader_name": "Mang Ye",
            "team_org": "Wuhan University",
            "team_size": 5,
        },
        {
            "team_name": "MIG",
            "leader_name": "Tao He",
            "team_org": "Tsinghua University",
            "team_size": 2,
        },
        {
            "team_name": "ISEE-ACW",
            "leader_name": "ancong wu",
            "team_org": "Sun Yat-sen University",
            "team_size": 4,
        },
        {
            "team_name": "Anonym",
            "leader_name": "Yukun Huang",
            "team_org": "University of Science and Technology of China",
            "team_size": 1,
        },
        {
            "team_name": "DrinkTea",
            "leader_name": "Xiao Liang",
            "team_org": "DOCOMO Beijing Communications Laboratories Co., Ltd.",
            "team_size": 5,
        },
        {
            "team_name": "Tardis",
            "leader_name": "Mingyang Zhang",
            "team_org": "Huazhong University of Science and Technology | AI Lab, ByteDance Inc., China |  Institute of High Performance Computing, A*STAR, Singapore",
            "team_size": 7,
        },
        {
            "team_name": "TerminusBazinga",
            "leader_name": "Rui Zhang",
            "team_org": "Terminus Group",
            "team_size": 1,
        },
        {
            "team_name": "snowdark",
            "leader_name": "Sun Yuxuan",
            "team_org": "Northwestern Polytechnical University",
            "team_size": 1,
        },
        {
            "team_name": "parrot_001",
            "leader_name": "Xuhong Guo",
            "team_org": "Docomo",
            "team_size": 1,
        },
        {
            "team_name": "rongrong",
            "leader_name": "siman zhang",
            "team_org": "JiuSi",
            "team_size": 1,
        },
        {
            "team_name": "Go for ReID",
            "leader_name": "Ruofei Gao",
            "team_org": "China Mobile Research Institute",
            "team_size": 2,
        },
        {
            "team_name": "？？？",
            "leader_name": "Haoyangl",
            "team_org": "University of Melbourne",
            "team_size": 1,
        },
        {
            "team_name": "Huaqiao university",
            "leader_name": "Yi Xie",
            "team_org": "Huaqiao university",
            "team_size": 7,
        },
        {
            "team_name": "EMJP",
            "leader_name": "Jiping Chen",
            "team_org": "Huaqiao University",
            "team_size": 1,
        },
        {
            "team_name": "xubc",
            "leader_name": "xubc",
            "team_org": "tsl",
            "team_size": 1,
        },
        {
            "team_name": "rabbit",
            "leader_name": "Yazhuo Guan",
            "team_org": "94",
            "team_size": 1,
        },
        {
            "team_name": "Victory",
            "leader_name": "Fangyuan Xie",
            "team_org": "Northwestern Polytechnical University",
            "team_size": 1,
        },
        {
            "team_name": "NoManCanControl",
            "leader_name": "Hui Fu",
            "team_org": "Northwestern Polytechnical University",
            "team_size": 1,
        },
        {
            "team_name": "Vanilla",
            "leader_name": "Xianpeng Zhu",
            "team_org": "Anhui University",
            "team_size": 3,
        },
        {
            "team_name": "NWPU_FlyingForDream",
            "leader_name": "Chao Li",
            "team_org": "Northwestern Polytechnical University",
            "team_size": 5,
        },
        {
            "team_name": "jiangnan",
            "leader_name": "Cheng NanJiang",
            "team_org": "Chengdu University of Information Technology",
            "team_size": 1,
        },
        {
            "team_name": "reidman",
            "leader_name": "丁金",
            "team_org": "UESTC",
            "team_size": 1,
        },
        {
            "team_name": "notthatsmart",
            "leader_name": "Tao lu",
            "team_org": "neu",
            "team_size": 1,
        },
        {
            "team_name": "PRGroup",
            "leader_name": "BeibeiLin",
            "team_org": "Beijing Jiaotong University",
            "team_size": 1,
        },
        {
            "team_name": "demo",
            "leader_name": "hello world",
            "team_org": "hust",
            "team_size": 1,
        },
        {
            "team_name": "Blazar Team",
            "leader_name": "Xiaoyan Lu",
            "team_org": "Southeast University",
            "team_size": 1,
        },
        {
            "team_name": "kafka",
            "leader_name": "Hailong Yang",
            "team_org": "myself",
            "team_size": 1,
        },
        {
            "team_name": "fly",
            "leader_name": "Tao Yang",
            "team_org": "Wuhan University of Technology",
            "team_size": 1,
        },
        {
            "team_name": "HUST_BB",
            "leader_name": "R.S. Wang",
            "team_org": "Huazhong University of Science and Technology",
            "team_size": 2,
        },
        {
            "team_name": "tfq568897492",
            "leader_name": "xiaoming jiang",
            "team_org": "zhimu keji",
            "team_size": 1,
        },
        {
            "team_name": "liuliu408",
            "leader_name": "liu qiang",
            "team_org": "Sichuan University",
            "team_size": 1,
        },
        {
            "team_name": "VisionX (Peng)",
            "leader_name": "peng zeng",
            "team_org": "yy",
            "team_size": 1,
        },
        {
            "team_name": "runone (9342)",
            "leader_name": "runone",
            "team_org": "runone",
            "team_size": 1,
        },
        {
            "team_name": "tangping",
            "leader_name": "lzy",
            "team_org": "HUST",
            "team_size": 3,
        },
        {
            "team_name": "SadFr0gs",
            "leader_name": "Liying Chi",
            "team_org": "None | University of Utah",
            "team_size": 2,
        },
        {
            "team_name": "A Rowing Boat",
            "leader_name": "Cong Wu",
            "team_org": "Jiangnan University",
            "team_size": 3,
        },
        {
            "team_name": "hust423",
            "leader_name": "lizongyi",
            "team_org": "Huazhong University of Science and Technology",
            "team_size": 5,
        },
        {
            "team_name": "June",
            "leader_name": "Zhiyuan Ma",
            "team_org": "None",
            "team_size": 1,
        },
        {
            "team_name": "F&T",
            "leader_name": "Di Yang",
            "team_org": "INRIA",
            "team_size": 4,
        },
        {
            "team_name": "HSSLAB",
            "leader_name": "Baoyu Fan",
            "team_org": "INSPUR",
            "team_size": 4,
        },
        {
            "team_name": "eagle eye",
            "leader_name": "Hao Fang",
            "team_org": "ZheJiang University",
            "team_size": 1,
        },
        {
            "team_name": "Hello Competition",
            "leader_name": "Liang Feifei",
            "team_org": "Civil Aviation University of China",
            "team_size": 1,
        },
        {
            "team_name": "Vactory",
            "leader_name": "Xiefangyuan",
            "team_org": "Northwestern Ploytechnical University",
            "team_size": 1,
        },
        {
            "team_name": "TeamHe",
            "leader_name": "Junjie He",
            "team_org": "Zhejiang University",
            "team_size": 1,
        },
        {
            "team_name": "Person0524",
            "leader_name": "Hanyang Jin",
            "team_org": "XJTU",
            "team_size": 2,
        },
        {
            "team_name": "chenww",
            "leader_name": "chenww",
            "team_org": "Alibaba",
            "team_size": 1,
        },
        {
            "team_name": "NZ",
            "leader_name": "zhuning",
            "team_org": "Harbin Engineering University",
            "team_size": 1,
        },
        {
            "team_name": "TuringTest",
            "leader_name": "Shenqi Lai",
            "team_org": "Xi’an Jiaotong University",
            "team_size": 2,
        },
        {
            "team_name": "ImageTru3d",
            "leader_name": "Baoping Li",
            "team_org": "ImageTru3d",
            "team_size": 1,
        },
        {
            "team_name": "MiemieSheep",
            "leader_name": "Wenxuan Liu",
            "team_org": "Wuhan University of Technology",
            "team_size": 4,
        },
        {
            "team_name": "CCCit",
            "leader_name": "Neo Chen",
            "team_org": "Alibaba",
            "team_size": 1,
        },
        {
            "team_name": "GoodAI",
            "leader_name": "Qiu Yuqing",
            "team_org": "OPPO",
            "team_size": 2,
        },
        {
            "team_name": "RE-AI",
            "leader_name": "siu yusuen",
            "team_org": "No Organization",
            "team_size": 2,
        },
        {
            "team_name": "Jingyu Xie",
            "leader_name": "jingyu Xie",
            "team_org": "TUM",
            "team_size": 1,
        },
        {
            "team_name": "TESTING",
            "leader_name": "TESTING",
            "team_org": "FOR TESTING ONLY",
            "team_size": 1,
        },
        {
            "team_name": "TWIOCAMIC",
            "leader_name": "Fei Wang",
            "team_org": "Beihang University",
            "team_size": 1,
        },
        {
            "team_name": "ABCDE",
            "leader_name": "Jingru Wang",
            "team_org": "BOE",
            "team_size": 1,
        },
        {
            "team_name": "RogersAI",
            "leader_name": "Wei-Yi Chang",
            "team_org": "RogersAI Technology",
            "team_size": 1,
        },
        {
            "team_name": "你笑起来真好看",
            "leader_name": "Zhengjian Wu",
            "team_org": "Xinjiang University",
            "team_size": 3,
        },
        {
            "team_name": "VisionX (Yuqiao)",
            "leader_name": "Yuqiao Xian",
            "team_org": "Sun Yat-sen University",
            "team_size": 1,
        },
        {
            "team_name": "underline",
            "leader_name": "Xiaoyu Zhu",
            "team_org": "Carnegie Mellon University",
            "team_size": 1,
        },
        {
            "team_name": "Star_Fire",
            "leader_name": "Xin Yuan",
            "team_org": "Wuhan University of Science and Technology",
            "team_size": 6,
        },
        {
            "team_name": "BIGbear",
            "leader_name": "Xiong Li",
            "team_org": "CETC",
            "team_size": 1,
        },
        {
            "team_name": "TaTa",
            "leader_name": "Yuhan Wang",
            "team_org": "Xidian University",
            "team_size": 4,
        },
        {
            "team_name": "WPIVISLab",
            "leader_name": "Yuping Shao",
            "team_org": "Worcester Polytechnic Institute",
            "team_size": 1,
        },
        {
            "team_name": "IPIU_VQA",
            "leader_name": "Zhicheng Guo",
            "team_org": "Xidian University",
            "team_size": 4,
        },
        {
            "team_name": "newbeeeee",
            "leader_name": "Quan Zhang",
            "team_org": "SUN YAT-SEN UNIVERSITY",
            "team_size": 1,
        },
        {
            "team_name": "FightXZ",
            "leader_name": "xuanzhao",
            "team_org": "CAMA ",
            "team_size": 1,
         }
    ]
}

export default RankingData
